# -*- mode: ruby -*-
# vi: set ft=ruby :

AWS_ACCESS_KEY_ID = ENV['AWS_ACCESS_KEY_ID']
AWS_ACCESS_KEY = ENV['AWS_ACCESS_KEY']

UBUNTU_TRUSTY_BOX_NAME = 'ubuntu/trusty64'

Vagrant.configure('2') do |config|
  config.vm.define :ubuntu_trusty do |local|
    local.vm.provider :virtualbox do |vb|
      vb.customize ['modifyvm', :id, '--memory', '1024']
    end
    local.vm.box = UBUNTU_TRUSTY_BOX_NAME
    local.vm.hostname = 'local'
    local.vm.synced_folder "../../", "/cloudify-packager", create: true
    local.vm.provision "shell" do |s|
      s.path = "provision.sh"
      s.args = "Ubuntu-trusty"
      s.privileged = false
    end
  end
end