language: python
python:
  - "2.7"
env:
    - TOX_ENV=docs
    - TOX_ENV=flake8
    - TOX_ENV=py27
# TODO: add coveralls support
install:
    - pip install tox
    # - pip install coveralls
script:
    - tox -e $TOX_ENV
# after_success:
#     coveralls
notifications:
  flowdock: e5a7316d704d3556833ca47bfaa62808

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2680a62f7b60e38039a9
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false