########
# Copyright (c) 2014 GigaSpaces Technologies Ltd. All rights reserved
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
#    * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    * See the License for the specific language governing permissions and
#    * limitations under the License.

# -*- mode: ruby -*-
# vi: set ft=ruby :

BASE_UBUNTU_BOX_NAME = 'precise64'
BASE_UBUNTU_BOX_URI = 'http://files.vagrantup.com/precise64.box'

BASE_CENTOS_BOX_NAME = 'centos6point4'
BASE_CENTOS_BOX_URI = 'https://github.com/2creatives/vagrant-centos/releases/download/v0.1.0/centos64-x86_64-20131030.box'

Vagrant.configure('2') do |config|

  config.vm.define :packman do |packman|

    packman_ip = '10.0.0.2'

    packman.vm.provider :virtualbox do |vb|
      vb.customize ['modifyvm', :id, '--memory', '1024']
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    end
    packman.vm.box = BASE_UBUNTU_BOX_NAME
    packman.vm.box_url = BASE_UBUNTU_BOX_URI
    packman.vm.network :private_network, ip: packman_ip
    packman.vm.hostname = 'packman'
    packman.vm.synced_folder "../packman/examples", "/home/vagrant/examples", create: true
    packman.vm.provision "shell", path: "provision.sh", privileged: true
  end

end