mapping = {
    'cannot_access_config_file': 1,
    'invalid_yaml_file': 2,
    'excluded_paths_must_be_a_list': 3,
    'string_failed_to_expand': 4,
    'no_paths_configured': 5,
    'file_not_found': 6,
    'type_path_collision': 7,
    'to_file_requires_explicit_path': 8,
    'validate_before_must_be_boolean': 9,
    'prevalidation_failed': 10,
    'no_config_found_for_package': 11,
    'excluded_conflict': 12,
    'packages_file_not_found': 13,
    'no_packages_defined': 14,
    'sources_empty': 15,
    'path_already_exists_no_overwrite': 16,
    'distro_not_supported': 17,
    'sources_path_required': 18,
    'sources_and_package_paths_identical': 19,
    'must_specify_file_or_dir': 20,
    'ppa_not_supported_by_distro': 21,
    'failed_create_package': 22,
    'module_could_not_be_installed': 23,
    'failed_to_download_file': 24,
    'failed_to_execute_command': 25,
    'package_types_must_be_list': 26,
    'unsupported_package_type': 27,
    'failed_to_download_module': 28,
    'targz_exists': 29,
    'failed_to_mkdir': 30,
    'distro not supported': 31,
    'package_must_be_of_type_dict': 32,
    'template_dir_must_be_of_type_string': 33,
    'template_dir_missing': 34,
    'template_file_must_be_of_type_string': 35,
    'template_file_missing': 36,
    'could_not_generate_template': 37,
    'could_not_write_to_file': 38,
    'failed_to_download_gem': 39,
    'overriding_modules_import_error': 40,

}
