mapping = {
    'cannot_access_config_file': 1,
    'invalid_yaml_file': 2,
    'excluded_paths_must_be_a_list': 3,
    'string_failed_to_expand': 4,
    'no_paths_configured': 5,
    'file_not_found': 6,
    'type_path_collision': 7,
    'to_file_requires_explicit_path': 8,
    'validate_before_must_be_boolean': 9,
    'prevalidation_failed': 10,
    'no_config_found_for_package': 11,
    'excluded_conflict': 12,
    'packages_file_not_found': 13,
    'no_packages_defined': 14,
    'sources_empty': 15,
    'path_already_exists_no_overwrite': 16,
    'distro_not_supported': 17,
    'sources_path_required': 18,
    'sources_and_package_paths_identical': 19,
    'must_specify_file_or_dir': 20,
}
